routes:
    /:
        controller: channel
        template: home
        filter: tag:sections

collections:
    /podcast/:
        permalink: /podcast/{slug}/
        template: custom-podcasts
        filter: primary_tag:podcast
